# Generated by Django 4.2.1 on 2023-11-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_buy_options_buy_idi_alter_status_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='idi',
            field=models.IntegerField(db_index=True, max_length=1000000, unique=True, verbose_name='id'),
        ),
    ]
