# Generated by Django 4.2.1 on 2023-11-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_buy_idi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='idi',
            field=models.IntegerField(auto_created=True, db_index=True, unique=True, verbose_name='id'),
        ),
    ]
