# Generated by Django 4.2.1 on 2023-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_buy_idi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='id',
        ),
        migrations.AlterField(
            model_name='buy',
            name='idi',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
